namespace Otrade.Application.DTOs.Security;

public class StartTwoFactorReplacementRequest
{
    public string Password { get; set; }
        = string.Empty;

    /*
     * Current Google Authenticator code
     * or one unused recovery code.
     */
    public string Code { get; set; }
        = string.Empty;
}

public class ConfirmTwoFactorReplacementRequest
{
    /*
     * Code generated by the new authenticator.
     */
    public string Code { get; set; }
        = string.Empty;
}

public class TwoFactorReplacementResponse
{
    public bool Replaced { get; set; }

    public bool RequiresLoginAgain { get; set; }

    public DateTime ReplacedAt { get; set; }

    public List<string> RecoveryCodes { get; set; }
        = new();
}

public class StartTwoFactorRecoveryRequest
{
    /*
     * Login challenge created only after the
     * email and password are verified.
     */
    public string ChallengeToken { get; set; }
        = string.Empty;

    public string Description { get; set; }
        = string.Empty;
}

public class StartTwoFactorRecoveryResponse
{
    /*
     * This token identifies the recovery request.
     * It is stored only in the browser session.
     */
    public string RecoveryToken { get; set; }
        = string.Empty;

    public string MaskedEmail { get; set; }
        = string.Empty;

    public DateTime EmailCodeExpiresAt { get; set; }

    public DateTime RequestExpiresAt { get; set; }
}

public class VerifyTwoFactorRecoveryEmailRequest
{
    public string RecoveryToken { get; set; }
        = string.Empty;

    public string Code { get; set; }
        = string.Empty;
}

public class TwoFactorRecoveryTokenRequest
{
    public string RecoveryToken { get; set; }
        = string.Empty;
}

public class TwoFactorRecoveryStatusResponse
{
    public string Status { get; set; }
        = string.Empty;

    public string Message { get; set; }
        = string.Empty;

    public DateTime CreatedAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public DateTime? WithdrawalLockedUntil { get; set; }
}

public class ReviewTwoFactorRecoveryRequest
{
    public string Note { get; set; }
        = string.Empty;
}

public class AdminTwoFactorRecoveryListItem
{
    public long RequestId { get; set; }

    public long UserId { get; set; }

    public string Uid { get; set; }
        = string.Empty;

    public string FullName { get; set; }
        = string.Empty;

    public string Email { get; set; }
        = string.Empty;

    public string KycStatus { get; set; }
        = string.Empty;

    public string Description { get; set; }
        = string.Empty;

    public DateTime CreatedAt { get; set; }

    public DateTime EmailVerifiedAt { get; set; }
}